[package]
name = "template_crate_name"
version = "1.0.0"
edition = "2021"
description = "Implement things as if rust had variadics"
homepage = "https://github.com/bevyengine/template_crate_name"
repository = "https://github.com/bevyengine/template_crate_name"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "variadics", "docs"]
rust-version = "1.81.0"
categories = ["macros", "utilities"]
exclude = ["tools/", ".github/"]
documentation = "https://docs.rs/template_crate_name"

[features]
default = ["alloc"]
alloc = []

[lib]

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[workspace]
exclude = ["benches", "compile_fail", "tools/compile_fail_utils"]
members = ["errors", ".", "benches"]

[workspace.lints.clippy]
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"

[workspace.lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

# Examples

[[example]]
name = "template_example_name"
path = "examples/demonstrations/template_example_name.rs"
doc-scrape-examples = true

[package.metadata.example.template_example_name]
name = "template_example_name"
description = "Demonstrates the functionality of `template_example_name`."
category = "Demonstration"
